name: Update Weather Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Menjalankan setiap 15 menit
  workflow_dispatch:
  
jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download JSON data
        run: |
          curl -o data.json "https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Soemarto%252C%2520Purwokerto/today?include=fcst%2Cobs%2Chistfcst%2Cstats%2Ccurrent&key=3UXRE8BPL2TKN9AQH99SESAYE&contentType=json"

      - name: Update JSON file in repository
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          mv data.json weather_data.json  # Ubah nama file jika perlu
          git add weather_data.json
          git commit -m "Update weather data" || true  # Lanjutkan jika tidak ada perubahan
          git push
